### ISSUE TITLE
Please port to Python3.12

### ISSUE THREAD

**Issue by tillea** [loads/molotov#164] opened 2024-01-15 19:48 UTC
I tried to upgrade the Debian molotov package in Debian where at the same time we want to support Python3.12.  Unfortunately the test suite is running into two failures which you can find [here in the full build log](https://salsa.debian.org/python-team/packages/python-molotov/-/jobs/5162570#L330).
Kind regards, Andreas.

**Comment by n1ngu** [comment] 2024-01-18 15:41
That was already implemented in https://github.com/tarekziade/molotov/pull/153 :thinking: 

Could that failure be due to some flaky test or some of your test suite configuration? Can you reproduce locally? (checking this repo out and running `tox -e py312` works just fine for me)

**Comment by n1ngu** [comment] 2024-01-18 16:08
`tox -e py312` also works in your fork, despite the fair amount of patches that you have on top of the upstream molotov. So I'd look into some CI runner configuration.

I'll close the issue because I don't see how we can help you, don't hesitate to ask for more help if something more concrete comes to your mind. Note python 3.12 IS supported.

Also, some of those patches of yours may deserve being merged upstream so be welcome to try to open a PR to reduce the burden of keeping your fork in sync.

Cheers.

**Closed as completed by n1ngu** 2024-01-18 16:08 UTC

**Comment by tillea** [comment] 2024-01-18 16:42
Thank you for your investigation into this issue.  I admit I'm not the maintainer of this package, just a team member who was trying to hunt down some random Python3.12 problems.  So I'll leave it to the actual Uploader of the Debian package whether he might create some PRs about this.  Since the patches all are just excluding some tests its not really astonishing that the patches do not affect the test suite in a negative manner.  For the moment I've added another patch excluding the two patches that were topic of this issue.
Kind regards, Andreas.
